
// CSS style format
// Attributes should be class properties
// Attribute values should match one of the property type's contructors

// TODO:
//     NonClient sections are not nested to simplfy the parser
//     Use class names to style ala HTML
//     Use Tag to specify "classes"

// Variables can be declared and used with $var syntax
// Colors => System.Drawing.KnownColor or HTML Code

@vals {
	windowColor: Green;
}

@modules {
	// Default is always System.Windows.Forms
	UxTest: paradoxlost.ux.test;
}

Form {
	$module: Default;
	AutoScaleMode: Dpi;
	Font: Segoe UI, 9.0, Regular;
	BackColor: $windowColor;

	// NonClient is special in that it doesn't represent an actual control
	// There is some fudge here that will be spelled out explicitly
	// NonClient.BackColor: $windowColor;

	Button {
		BackColor: ControlDarkDark;
	}
}

Form2 {
	$module: UxTest;
	BackColor: Blue;

	Button {
		$module: Default;
		BackColor: White;
		Enabled: false;
		ForeColor: Blue;
		FlatStyle: Flat;
		FlatAppearance.BorderSize: 4;
		FlatAppearance.BorderColor: Red;
	}
}

