
// CSS style format
// Attributes should be class properties
// Attribute values should match one of the property type's contructors

// TODO:
//     NonClient sections are not nested to simplfy the parser
//     Use class names to style ala HTML
//     Use Tag to specify "classes"

// Variables can be declared and used with $var syntax
// Colors => System.Drawing.KnownColor or HTML Code

@var {
	windowColor: Green;
}


Form {
	AutoScaleMode = Dpi;
	Font: Segoe UI, 9.0, Regular;
	BackColor: $windowColor;

	// NonClient is special in that it doesn't represent an actual control
	// There is some fudge here that will be spelled out explicitly
	// NonClient.BackColor: $windowColor;
}

//Form2 {
//	BackColor: Blue;
//}

Button {
	BackColor: ControlDarkDark;
}